import { escapeRegExp } from "@pan/types";

const PRE_FILTER_LIST = [
  "- Movie",
  "- OVA",
  "- TV",
  "- WEB",
  "+ Movie",
  "+ OAD",
  "+ OVA",
  "+ SP",
  "+ Tokuten BD",
  "+ Tokuten DVD",
  "+Movie",
  "+OVA",
  "+Specials",
  "+SP",
  "10 bits",
  "10-bit",
  "1024x",
  "1080p",
  "10Bit",
  "1280x",
  "1920x",
  "2160p",
  "480p",
  "720p",
  "HE-AAC",
  "AAC2.0",
  "AAC",
  "AC-3",
  "AC3",
  "AVC",
  "Airota",
  "ANK-Raws",
  "Batch",
  "Beatrice-Raws",
  "BD Batch",
  "BD Box",
  "BD Remux",
  "BD-BOX",
  "BDRIP",
  "BDRip",
  "BeanSub",
  "BlueLobster",
  "Bluray",
  "CASO",
  "DD+",
  "DDP5.1",
  "DMG",
  "DTS",
  "Dual Audio",
  "Dual-Audio",
  "DVD-BOX",
  "DVDISO",
  "DVDRip",
  "EMBER",
  "Eng-Subs",
  "Eng-Sub",
  "EnkanRec",
  "Erai-raws",
  "FLAC",
  "FLsnow",
  "FZSD",
  "H.264",
  "H264",
  "HDR10",
  "HEVC",
  "Hi10P",
  "HQR",
  "IrizaRaws",
  "Judas",
  "&Kamigami",
  "Kamigami&",
  "[Kamigami]",
  "KitaujiSub",
  "Lemonade&",
  "&Lemonade",
  "Liuyun",
  "LoliHouse",
  "LowPower-Raws",
  "LP-Raws",
  "LPSub",
  "Ma10p",
  "Ma444-10p",
  "Moozzi2",
  "Multi Sub",
  "Multi-Subs",
  "Multiple Subtitle",
  "NAOKI-Raws",
  "NekoHost-Raws",
  "Nekomoe kissaten",
  "NFLX",
  "philosophy-raws",
  "ReinForce",
  "Snow-Raws",
  "Sumisora",
  "SweetSub",
  "tlacatlc6",
  "Taedium",
  "THD",
  "TrueHD",
  "TRUE-HD",
  "U2-Rip",
  "U3-Web",
  "UCCUSS",
  "UHA-WINGS",
  "VCB-Studio",
  "VCB-S",
  "Ver.",
  "VFR",
  "WEB-DL",
  "WEBRip",
  "x264",
  "x265",
  "x720",
  "XKsub",
  "Yousei-raws",
  "YUV420P10",
] as const;

export const PRE_FILTER_REGEX = new RegExp(
  PRE_FILTER_LIST.map(escapeRegExp).join("|"),
  "gi"
);

export const RESIDUE_REGEX = [
  /\([^a-wyzA-Z\u4e00-\u9fff]*\)/g,
  /\[[^a-wyzA-Z\u4e00-\u9fff]*\]/g,
  /\([\s\d]*(BD|DVD)[\s\d]*\)/g,
  /\[[\s\d]*(BD|DVD)[\s\d]*\]/g,
  /[\(\[]*\d+\s*(-|~)\s*\d+\s*(Fin|Complete|)\s*[\)\]]*\s*$/g,
  /-\s*$/g,
  /^[\s\d\-\(\)\[\]]*(Season|S)*[\s\d\-\(\)\[\]]*$/g,
] as const;

export const VIDEO_REGEX = /(\.mkv|\.mp4|\.bdmv)$/i;
